apiVersion: apps/v1
kind: Deployment
metadata:
  name: airline-deployment
  labels:
    app: airline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airline
  template:
    metadata:
      labels:
        app: airline
    spec:
      containers:
      - name: airline
        image: bdocker971/airline:v7
        ports:
        - containerPort: 160     
---
apiVersion: v1
kind: Service
metadata:
  name: airline-svc    
spec:
  type: LoadBalancer
  selector:
    app: airline
  ports:
    - protocol: TCP
      port: 160
    
      